// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5PM1ErCcNWw5JVPocZSKDpdXCrXqKmjg',
    appId: '1:976682532304:web:b29659b6e3f60963ba0dd5',
    messagingSenderId: '976682532304',
    projectId: 'potfolio-cb6f8',
    authDomain: 'potfolio-cb6f8.firebaseapp.com',
    storageBucket: 'potfolio-cb6f8.firebasestorage.app',
    measurementId: 'G-4GTBZEFEBZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIfxhh5f8mT4RKr7i-8jcc-uWtq4O99c',
    appId: '1:976682532304:ios:d94ea1af12539dafba0dd5',
    messagingSenderId: '976682532304',
    projectId: 'potfolio-cb6f8',
    storageBucket: 'potfolio-cb6f8.firebasestorage.app',
    iosBundleId: 'com.example.yelwinoo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJN8OMYcXusLE53eNTCz3eZ84T8bVm4-A',
    appId: '1:976682532304:android:009da756d50e58a3ba0dd5',
    messagingSenderId: '976682532304',
    projectId: 'potfolio-cb6f8',
    storageBucket: 'potfolio-cb6f8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5PM1ErCcNWw5JVPocZSKDpdXCrXqKmjg',
    appId: '1:976682532304:web:782a21ae1ef76f01ba0dd5',
    messagingSenderId: '976682532304',
    projectId: 'potfolio-cb6f8',
    authDomain: 'potfolio-cb6f8.firebaseapp.com',
    storageBucket: 'potfolio-cb6f8.firebasestorage.app',
    measurementId: 'G-DRKQ4FGE47',
  );
}
